# Makefile for rproxy

# Compiler
CC = gcc

# Compiler flags
CFLAGS = -Wall -pthread

# Name of the binary output
TARGET = rproxy

# Source files
SRCS = rproxy.c

# Object files (auto-generated by make)
OBJS = $(SRCS:.c=.o)

# Default target (compile the program)
all: $(TARGET)

# Link the object files to create the binary
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# Rule to compile .c files to .o object files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Clean up the object files and binary
clean:
	rm -f $(OBJS) $(TARGET)

# Install the binary to /usr/local/bin
install: $(TARGET)
	cp $(TARGET) /usr/local/bin/$(TARGET)

# Uninstall the binary from /usr/local/bin
uninstall:
	rm -f /usr/local/bin/$(TARGET)
